---
version: 1
disable_existing_loggers: False


formatters:
    simple:
        format: "%(asctime)s %(module)s [%(levelname)s]: %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

    verbose:
        format: '%(asctime)s %(module)s %(threadName)s [%(levelname)s]: %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: {filepath}/logs/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    info_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: {filepath}/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: {filepath}/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    quartzscrapers:
        level: DEBUG
        handlers:
        - console
        - debug_file
        - info_file
        - error_file
        propagate: yes
...
